
AllCops:
 Exclude:
    - 'vendor/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'public/system/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'db/seeds.rb'
    - 'config/database.yml'
    - 'config/secrets.yml'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

Lint/MissingSuper:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Naming/VariableNumber:
  Enabled: false
