version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
